name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Cache ./downloads
        uses: actions/cache@v4
        with:
          path: downloads
          key: downloads
      - run: make
      - run: ls ./output
